
const DEFAULT_SUCCESS_STATUS = 0;
const DEFAULT_SUCCESS_MESSAGE = 'success';

const DEFAULT_FAIL_STATUS = -1;
const DEFAULT_FAIL_MESSAGE = 'fail';

module.exports = {
    DEFAULT_SUCCESS_STATUS,
    DEFAULT_SUCCESS_MESSAGE,

    DEFAULT_FAIL_STATUS,
    DEFAULT_FAIL_MESSAGE,

}